print "=================================="
print "= Reading lights SConscript File ="
print "=================================="
print 

Import(['clean_envs'])

tools_env = clean_envs['userspace'].Clone()

accessories_srcs = Split('''
    wifi_plug.cpp
''')

accessories_lib = tools_env.Library('accessories', accessories_srcs)

tools_env['LIBS'].append(accessories_lib)

if ARGUMENTS.get('VERBOSE') != '1':
    tools_env['CCCOMSTR'] = "Compiling $TARGET"
    tools_env['LINKCOMSTR'] = "Linking $TARGET"
