env = Environment()
debug = ARGUMENTS.get('debug', 0)
if int(debug):
	env.Append(CCFLAGS = '-g')

env.Library('libfft', ['lib/libfft.c'])

env.Library(
	'libbeatmatch', 
	['beatmatch.cpp', 'beatmatchevent.cpp'], 
	LIBS = ['libasound', 'libportaudio', 'libm', 'libfft'], 
	LIBPATH = ['/usr/local/lib', '.'],
	LINKFLAGS = ["-lpthread"]
)

env.Program(
	'beatmatchtest.cpp', 
	LIBS=['libasound', 'libportaudio', 'libm', 'libbeatmatch', 'libfft'], 
	LIBPATH=['/usr/local/lib', '.'], 
	LINKFLAGS=["-lpthread"]
)